version: '3'

networks:
  app-network:
    driver: bridge


services:
  frontend:
    build:
      context: ./nurseduty_frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_URL=${VUE_APP_API_URL}
    ports:
      - "6200:80" 
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./nurseduty_backend
      dockerfile: Dockerfile
    volumes:
      - ./nurseduty_backend/data:/app/data
    networks:
      - app-network
    ports:
      - "6200:6200"